### ISSUE TITLE
No connection to database

### ISSUE THREAD

**Issue by alvaro-octal** [pavog/Statistics-Bukkit-Plugin#3]
Hi,

firstly, thanks for maintaining this plugin. I came from Statistics 1.2.4, and everything worked fine until Spigot 1.11, then I found your version but I'm unable to connect database, so... turned debug into `true` and:

```
[23:04:06] [Server thread/INFO]: Me issued server command: /plugman reload Statistics
[23:04:06] [Server thread/INFO]: [Statistics] Disabling Statistics v1.3.0
[23:04:14] [Server thread/INFO]: [Statistics] +-------- [ Hook Manager ] --------+
[23:04:14] [Server thread/INFO]: [Statistics] |    Hook Manager shutting down    |
[23:04:14] [Server thread/INFO]: [Statistics] |                                  |
[23:04:14] [Server thread/INFO]: [Statistics] +----------------------------------+
[23:04:14] [Server thread/INFO]: [Statistics] Enabling Statistics v1.3.0
[23:04:14] [Server thread/INFO]: [Statistics] +------ [ Fetching Patches ] ------+
[23:04:14] [Server thread/INFO]: [Statistics] |  All patch files are up to date  |
[23:04:14] [Server thread/INFO]: [Statistics] +----------------------------------+
[23:04:14] [Server thread/INFO]: [Statistics] Database connection established.
[23:04:14] [Server thread/INFO]: [Statistics] +-------- [ Hook Manager ] --------+
[23:04:14] [Server thread/INFO]: [Statistics] |     Hook Manager starting up     |
[23:04:14] [Server thread/INFO]: [Statistics] |                                  |
[23:04:14] [Server thread/INFO]: [Statistics] |                                  |
[23:04:14] [Server thread/INFO]: [Statistics] |         0 hooks enabled          |
[23:04:14] [Server thread/INFO]: [Statistics] +----------------------------------+
[23:04:14] [Server thread/INFO]: [Statistics] Starting to register commands
[23:04:14] [Server thread/INFO]: [Statistics] Scanning com.wolvencraft.yasp.cmd.DatabaseCommands for command methods (14 total)
[23:04:14] [Server thread/INFO]: [Statistics] Registering a command with alias: repatch
[23:04:14] [Server thread/INFO]: [Statistics] Registering a command with alias: dump
[23:04:14] [Server thread/INFO]: [Statistics] Registering a command with alias: reconnect
[23:04:14] [Server thread/INFO]: [Statistics] Registering a command with alias: patch
[23:04:14] [Server thread/INFO]: [Statistics] Registering a command with alias: sync
[23:04:14] [Server thread/INFO]: [Statistics] Scanning com.wolvencraft.yasp.cmd.PlayerCommands for command methods (11 total)
[23:04:14] [Server thread/INFO]: [Statistics] Registering a command with alias: book
[23:04:14] [Server thread/INFO]: [Statistics] Registering a command with alias: scoreboard
[23:04:14] [Server thread/INFO]: [Statistics] Scanning com.wolvencraft.yasp.cmd.PluginCommands for command methods (12 total)
[23:04:14] [Server thread/INFO]: [Statistics] Registering a command with alias: pause
[23:04:14] [Server thread/INFO]: [Statistics] Registering a command with alias: remove
[23:04:14] [Server thread/INFO]: [Statistics] Registering a command with alias: help
[23:04:14] [Server thread/INFO]: [Statistics] StatsBookListener loads
[23:04:14] [Craft Scheduler Thread - 3403/INFO]: [Statistics] Refreshing Online Session Cache.
[23:04:14] [Server thread/INFO]: [Statistics] Creating a new user session for someOtherUser1(#0)
[23:04:14] [Server thread/INFO]: [Statistics] Creating a new user session for someOtherUser2(#1)
[23:04:14] [Craft Scheduler Thread - 3407/INFO]: [Statistics] Creating a new user session for someOtherUser(#2)
[23:04:14] [Server thread/INFO]: [Statistics] Creating a new user session for someUser (#3)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] +-------------- [ Statistics ] --------------+
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | The plugin 'Statistics' has caused an error.
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | Please, create a new ticket with this error at
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | http://dev.bukkit.org/bukkit-mods/Statistics/
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | 
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | Bukkit   : git-Spigot-bfe6acd-b5b0a97 (MC: 1.11)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | Plugin   : Statistics v1.3.0
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | Version  : 1.3.0
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | Error    : com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] |            Cannot add or update a child row: a foreign key constraint fails (`Statistics`.`stats_total_pve_kills`, CONSTRAINT `stats_fk_player_id13` FOREIGN KEY (`player_id`) REFERENCES `stats_players` (`player_id`) ON DELETE CASCADE ON UPDATE NO ACTION)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] +--------------------------------------------+
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | The stack trace of the error follows: 
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | 
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at sun.reflect.GeneratedConstructorAccessor329.newInstance(Unknown Source)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.mysql.jdbc.Util.getInstance(Util.java:387)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1540)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2595)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1468)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.wolvencraft.yasp.db.Database.executeUpdate(Database.java:292)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.wolvencraft.yasp.db.Query.executeUpdate(Query.java:80)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.wolvencraft.yasp.db.Query.access$100(Query.java:39)
[23:04:14] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.wolvencraft.yasp.db.Query$DatabaseQuery.insert(Query.java:464)
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.wolvencraft.yasp.db.data.pve.TotalPVEStats.fetchData(TotalPVEStats.java:86)
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.wolvencraft.yasp.db.data.pve.TotalPVEStats.<init>(TotalPVEStats.java:62)
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.wolvencraft.yasp.db.data.pve.PVEData.getNormalData(PVEData.java:57)
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.wolvencraft.yasp.db.data.pve.PVEData.playerKilledCreature(PVEData.java:69)
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.wolvencraft.yasp.session.OnlineSession.killedCreature(OnlineSession.java:246)
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at com.wolvencraft.yasp.listeners.handlers.DeathHandler$MonsterDeath.run(DeathHandler.java:163)
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | at java.lang.Thread.run(Thread.java:745)
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | Multiple errors might have occurred, only
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] | one stack trace is shown.
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] +--------------------------------------------+
[23:04:15] [Craft Scheduler Thread - 3402/INFO]: [Statistics] Connection is still present. Malformed query detected.
[23:04:15] [Craft Scheduler Thread - 3561/INFO]: [Statistics] Took 0ms to retrieve SergiCasas's ID from cache.
[23:04:15] [Craft Scheduler Thread - 3578/INFO]: [Statistics] Took 0ms to retrieve Robotox's ID from cache.
[23:04:15] [Craft Scheduler Thread - 3596/INFO]: [Statistics] Took 0ms to retrieve Manthekilla's ID from cache.
[23:04:15] [Craft Scheduler Thread - 3616/INFO]: [Statistics] Took 0ms to retrieve Itz_Diego_'s ID from cache.
[23:04:15] [Craft Scheduler Thread - 3402/WARN]: [Statistics] Plugin Statistics v1.3.0 generated an exception while executing task 4353880
java.lang.NullPointerException
    at com.wolvencraft.yasp.session.OnlineSession.killedCreature(OnlineSession.java:247) ~[?:?]
    at com.wolvencraft.yasp.listeners.handlers.DeathHandler$MonsterDeath.run(DeathHandler.java:163) ~[?:?]
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-bfe6acd-b5b0a97]
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-bfe6acd-b5b0a97]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] +-------------- [ Statistics ] --------------+
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | The plugin 'Statistics' has caused an error.
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | Please, create a new ticket with this error at
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | http://dev.bukkit.org/bukkit-mods/Statistics/
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | 
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | Bukkit   : git-Spigot-bfe6acd-b5b0a97 (MC: 1.11)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | Plugin   : Statistics v1.3.0
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | Version  : 1.3.0
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | Error    : com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] |            Cannot add or update a child row: a foreign key constraint fails (`Statistics`.`stats_total_pve_kills`, CONSTRAINT `stats_fk_player_id13` FOREIGN KEY (`player_id`) REFERENCES `stats_players` (`player_id`) ON DELETE CASCADE ON UPDATE NO ACTION)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] +--------------------------------------------+
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | The stack trace of the error follows: 
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | 
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at sun.reflect.GeneratedConstructorAccessor329.newInstance(Unknown Source)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.mysql.jdbc.Util.getInstance(Util.java:387)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1540)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2595)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1468)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.wolvencraft.yasp.db.Database.executeUpdate(Database.java:292)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.wolvencraft.yasp.db.Query.executeUpdate(Query.java:80)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.wolvencraft.yasp.db.Query.access$100(Query.java:39)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.wolvencraft.yasp.db.Query$DatabaseQuery.insert(Query.java:464)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.wolvencraft.yasp.db.data.pve.TotalPVEStats.fetchData(TotalPVEStats.java:86)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.wolvencraft.yasp.db.data.pve.TotalPVEStats.<init>(TotalPVEStats.java:62)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.wolvencraft.yasp.db.data.pve.PVEData.getNormalData(PVEData.java:57)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.wolvencraft.yasp.db.data.pve.PVEData.playerKilledCreature(PVEData.java:69)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.wolvencraft.yasp.session.OnlineSession.killedCreature(OnlineSession.java:246)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at com.wolvencraft.yasp.listeners.handlers.DeathHandler$MonsterDeath.run(DeathHandler.java:163)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | at java.lang.Thread.run(Thread.java:745)
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | Multiple errors might have occurred, only
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] | one stack trace is shown.
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] +--------------------------------------------+
[23:04:15] [Craft Scheduler Thread - 3407/INFO]: [Statistics] Connection is still present. Malformed query detected.
[23:04:15] [Craft Scheduler Thread - 3407/WARN]: [Statistics] Plugin Statistics v1.3.0 generated an exception while executing task 4353905
java.lang.NullPointerException
    at com.wolvencraft.yasp.session.OnlineSession.killedCreature(OnlineSession.java:247) ~[?:?]
    at com.wolvencraft.yasp.listeners.handlers.DeathHandler$MonsterDeath.run(DeathHandler.java:163) ~[?:?]
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-bfe6acd-b5b0a97]
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-bfe6acd-b5b0a97]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[23:04:15] [Craft Scheduler Thread - 3616/INFO]: [Statistics] Session is ready!
[23:04:15] [Craft Scheduler Thread - 3578/INFO]: [Statistics] Session is ready!
[23:04:15] [Craft Scheduler Thread - 3561/INFO]: [Statistics] Session is ready!
[23:04:15] [Craft Scheduler Thread - 3596/INFO]: [Statistics] Session is ready!
[23:04:17] [Finalizer/ERROR]: [Statistics] Failed to re-connect to the database. Data is being stored locally.
[23:04:17] [Finalizer/ERROR]: [Statistics] Failed to re-connect to the database. Data is being stored locally.
[23:04:17] [Finalizer/ERROR]: [Statistics] Failed to re-connect to the database. Data is being stored locally.
[23:04:17] [Finalizer/ERROR]: [Statistics] Failed to re-connect to the database. Data is being stored locally.
[23:04:17] [Finalizer/ERROR]: [Statistics] Failed to re-connect to the database. Data is being stored locally.
[23:04:17] [Finalizer/ERROR]: [Statistics] Failed to re-connect to the database. Data is being stored locally.
[23:04:17] [Finalizer/ERROR]: [Statistics] Failed to re-connect to the database. Data is being stored locally.
[23:04:17] [Finalizer/ERROR]: [Statistics] Failed to re-connect to the database. Data is being stored locally.
[23:04:17] [Finalizer/ERROR]: [Statistics] Failed to re-connect to the database. Data is being stored locally.
[23:04:17] [Finalizer/ERROR]: [Statistics] Failed to re-connect to the database. Data is being stored locally.
[23:04:17] [Finalizer/ERROR]: [Statistics] Failed to re-connect to the database. Data is being stored locally.
[23:04:17] [Finalizer/ERROR]: [Statistics] Failed to re-connect to the database. Data is being stored locally.
[23:04:19] [Craft Scheduler Thread - 3596/INFO]: [Statistics] Creating a new user session for someUser(#4)
[23:04:19] [Craft Scheduler Thread - 3594/INFO]: [Statistics] Took 0ms to retrieve someUser's ID from cache.
[23:04:20] [Craft Scheduler Thread - 3594/INFO]: [Statistics] Session is ready!
[23:04:20] [Craft Scheduler Thread - 3596/INFO]: [Statistics] Session is ready!
[23:04:20] [Craft Scheduler Thread - 3426/INFO]: [Statistics] Session is ready!
[23:04:20] [Craft Scheduler Thread - 3407/INFO]: [Statistics] Session is ready!
[23:04:20] [Craft Scheduler Thread - 3616/INFO]: [Statistics] Session is ready!
[23:04:21] [Craft Scheduler Thread - 3578/INFO]: [Statistics] Session is ready!
[23:04:21] [Craft Scheduler Thread - 3400/INFO]: [Statistics] Session is ready!
[23:04:21] [Craft Scheduler Thread - 3561/INFO]: [Statistics] Session is ready!
```

thanks in advance

**Comment by pavog** [comment]
Hi, thanks for your report!

Seems like something is wrong with your database.
Are the patches in the plugins folder?
It seems like they have not got executed...

**Comment by alvaro-octal** [comment]
It doesn't seems they have been even created, but directory permissions are OK. (22 of April is Statistics (nearly) installation date)

![captura de pantalla 2016-11-28 a las 18 53 35](https://cloud.githubusercontent.com/assets/4562922/20679620/029356e8-b59c-11e6-88c0-e37642e8094e.png)

**Comment by pavog** [comment]
Mhhh... You could try to extract them manually into the patches folder and reload the plugin.

**Comment by alvaro-octal** [comment]
forgot to close this, some days after my last message it fixed itself, probably spigot's fault, or misconfiguration... thanks anyway.
